/* ============================================================
   data.js — BornHistory.com
   Music & Films database 1920–2024
   Every year covered individually
   ============================================================ */

window.MUSIC_DB = {
  1920:['Whispering – Paul Whiteman','Avalon – Al Jolson','Margie – Original Dixieland Jass Band'],
  1921:['Ain\'t We Got Fun – Van & Schenck','April Showers – Al Jolson','Wang Wang Blues – Paul Whiteman'],
  1922:['Chicago – Isham Jones','Toot Toot Tootsie – Al Jolson','My Buddy – Al Jolson'],
  1923:['Yes! We Have No Bananas – Billy Jones','Who\'s Sorry Now – Van & Schenck','Barney Google – Billy Jones'],
  1924:['It Had to Be You – Isham Jones','Tea for Two – Marion Harris','California Here I Come – Al Jolson'],
  1925:['Sweet Georgia Brown – Ben Bernie','Show Me the Way to Go Home – Irving King','Five Foot Two Eyes of Blue – Art Landry'],
  1926:['The Blue Room – Sam Lanin','Baby Face – Jan Garber','Valencia – Paul Whiteman'],
  1927:['My Blue Heaven – Gene Austin','Ol\' Man River – Paul Whiteman','Among My Souvenirs – Paul Whiteman'],
  1928:['Ramona – Gene Austin','Makin\' Whoopee – Eddie Cantor','Lover Come Back to Me – Paul Whiteman'],
  1929:['Tiptoe Through the Tulips – Nick Lucas','Singing in the Rain – Cliff Edwards','Stardust – Isham Jones'],
  1930:['Happy Days Are Here Again – Ben Selvin','Georgia on My Mind – Hoagy Carmichael','Body and Soul – Paul Whiteman'],
  1931:['Minnie the Moocher – Cab Calloway','Wrap Your Troubles in Dreams – Bing Crosby','When the Moon Comes Over the Mountain – Kate Smith'],
  1932:['Brother Can You Spare a Dime – Rudy Vallee','Night and Day – Fred Astaire','How Deep Is the Ocean – Bing Crosby'],
  1933:['Smoke Gets in Your Eyes – Paul Whiteman','Stormy Weather – Leo Reisman','Easter Parade – Clifton Webb'],
  1934:['Blue Moon – Glen Gray','The Continental – Leo Reisman','Cocktails for Two – Duke Ellington'],
  1935:['Cheek to Cheek – Fred Astaire','Begin the Beguine – Artie Shaw','I Got Rhythm – Ethel Merman'],
  1936:['These Foolish Things – Benny Goodman','Pennies from Heaven – Bing Crosby','I\'ve Got You Under My Skin – Virginia Verrill'],
  1937:['Bei Mir Bist Du Schoen – Andrews Sisters','That Old Feeling – Shep Fields','Sweet Leilani – Bing Crosby'],
  1938:['A-Tisket A-Tasket – Ella Fitzgerald','My Heart Belongs to Daddy – Mary Martin','September Song – Walter Huston'],
  1939:['Over the Rainbow – Judy Garland','God Bless America – Kate Smith','South of the Border – Gene Autry'],
  1940:['When You Wish Upon a Star – Cliff Edwards','In the Mood – Glenn Miller','Only Forever – Bing Crosby'],
  1941:['Chattanooga Choo Choo – Glenn Miller','Green Eyes – Jimmy Dorsey','Daddy – Sammy Kaye'],
  1942:['White Christmas – Bing Crosby','Moonlight Cocktail – Glenn Miller','Tangerine – Jimmy Dorsey'],
  1943:['Paper Doll – Mills Brothers','You\'ll Never Know – Dick Haymes','Sunday Monday or Always – Bing Crosby'],
  1944:['Swinging on a Star – Bing Crosby','Long Ago and Far Away – Jo Stafford','I\'ll Walk Alone – Dinah Shore'],
  1945:['Sentimental Journey – Doris Day','Till the End of Time – Perry Como','On the Atchison Topeka and Santa Fe – Johnny Mercer'],
  1946:['Prisoner of Love – Perry Como','To Each His Own – Eddy Howard','The Gypsy – Ink Spots'],
  1947:['Near You – Francis Craig','Peg O\' My Heart – Harmonicats','I Wish I Didn\'t Love You So – Vaughn Monroe'],
  1948:['Buttons and Bows – Dinah Shore','Nature Boy – Nat King Cole','Twelfth Street Rag – Pee Wee Hunt'],
  1949:['Riders in the Sky – Vaughn Monroe','That Lucky Old Sun – Frankie Laine','Some Enchanted Evening – Perry Como'],
  1950:['Goodnight Irene – Leadbelly & Weavers','Tennessee Waltz – Patti Page','Mona Lisa – Nat King Cole'],
  1951:['Too Young – Nat King Cole','Because of You – Tony Bennett','Come On-a My House – Rosemary Clooney'],
  1952:['Blue Tango – Leroy Anderson','Wheel of Fortune – Kay Starr','Cry – Johnnie Ray'],
  1953:['Vaya Con Dios – Les Paul & Mary Ford','Song from Moulin Rouge – Percy Faith','I Believe – Frankie Laine'],
  1954:['Sh-Boom – Crew-Cuts','Little Things Mean a Lot – Kitty Kallen','Oh! My Pa-Pa – Eddie Fisher'],
  1955:['Rock Around the Clock – Bill Haley','Sixteen Tons – Tennessee Ernie Ford','Ain\'t That a Shame – Fats Domino'],
  1956:['Heartbreak Hotel – Elvis Presley','Don\'t Be Cruel – Elvis Presley','Hound Dog – Elvis Presley'],
  1957:['All Shook Up – Elvis Presley','Jailhouse Rock – Elvis Presley','Tammy – Debbie Reynolds'],
  1958:['Volare – Domenico Modugno','Little Star – Elegants','Patricia – Perez Prado'],
  1959:['Mack the Knife – Bobby Darin','Battle of New Orleans – Johnny Horton','Venus – Frankie Avalon'],
  1960:['It\'s Now or Never – Elvis Presley','Are You Lonesome Tonight – Elvis Presley','Running Scared – Roy Orbison'],
  1961:['Tossin\' and Turnin\' – Bobby Lewis','I Fall to Pieces – Patsy Cline','Michael – Highwaymen'],
  1962:['Stranger on the Shore – Mr. Acker Bilk','I Can\'t Stop Loving You – Ray Charles','Mashed Potato Time – Dee Dee Sharp'],
  1963:['Sugar Shack – Jimmy Gilmer','He\'s So Fine – Chiffons','Hey Paula – Paul & Paula'],
  1964:['I Want to Hold Your Hand – The Beatles','She Loves You – The Beatles','Hello Dolly – Louis Armstrong'],
  1965:['(I Can\'t Get No) Satisfaction – The Rolling Stones','Like a Rolling Stone – Bob Dylan','Help! – The Beatles'],
  1966:['The Ballad of the Green Berets – SSgt Barry Sadler','Reach Out I\'ll Be There – Four Tops','96 Tears – ? and the Mysterians'],
  1967:['To Sir With Love – Lulu','The Letter – Box Tops','Ode to Billie Joe – Bobbie Gentry'],
  1968:['Hey Jude – The Beatles','Honey – Bobby Goldsboro','Love Child – Diana Ross & Supremes'],
  1969:['Sugar Sugar – Archies','Aquarius/Let the Sunshine In – 5th Dimension','I Can\'t Get Next to You – Temptations'],
  1970:['Bridge Over Troubled Water – Simon & Garfunkel','Let It Be – The Beatles','In the Summertime – Mungo Jerry'],
  1971:['Joy to the World – Three Dog Night','Maggie May – Rod Stewart','It\'s Too Late – Carole King'],
  1972:['The First Time Ever I Saw Your Face – Roberta Flack','American Pie – Don McLean','Without You – Nilsson'],
  1973:['Tie a Yellow Ribbon – Dawn','Bad Bad Leroy Brown – Jim Croce','Killing Me Softly – Roberta Flack'],
  1974:['The Way We Were – Barbra Streisand','Seasons in the Sun – Terry Jacks','Come and Get Your Love – Redbone'],
  1975:['Bohemian Rhapsody – Queen','Fame – David Bowie','Dancing Queen – ABBA'],
  1976:['Tonight\'s the Night – Rod Stewart','Silly Love Songs – Wings','Don\'t Go Breaking My Heart – Elton John & Kiki Dee'],
  1977:['You Light Up My Life – Debby Boone','Hotel California – Eagles','I Just Want to Be Your Everything – Andy Gibb'],
  1978:['Night Fever – Bee Gees','Shadow Dancing – Andy Gibb','Stayin\' Alive – Bee Gees'],
  1979:['My Sharona – Knack','Bad Girls – Donna Summer','Le Freak – Chic'],
  1980:['Another One Bites the Dust – Queen','Call Me – Blondie','Lady – Kenny Rogers'],
  1981:['Endless Love – Diana Ross & Lionel Richie','Physical – Olivia Newton-John','Bette Davis Eyes – Kim Carnes'],
  1982:['I Love Rock\'n\'Roll – Joan Jett','Eye of the Tiger – Survivor','Ebony and Ivory – Paul McCartney & Stevie Wonder'],
  1983:['Every Breath You Take – The Police','Say Say Say – McCartney & Jackson','Total Eclipse of the Heart – Bonnie Tyler'],
  1984:['When Doves Cry – Prince','Jump – Van Halen','Wake Me Up Before You Go-Go – Wham!'],
  1985:['We Are the World – USA for Africa','Careless Whisper – George Michael','Like a Virgin – Madonna'],
  1986:['That\'s What Friends Are For – Dionne & Friends','Walk Like an Egyptian – Bangles','Greatest Love of All – Whitney Houston'],
  1987:['Walk Like an Egyptian – Bangles','Alone – Heart','La Bamba – Los Lobos'],
  1988:['Faith – George Michael','Need You Tonight – INXS','Got My Mind Set on You – George Harrison'],
  1989:['Look Away – Chicago','Miss You Much – Janet Jackson','Another Day in Paradise – Phil Collins'],
  1990:['Nothing Compares 2 U – Sinéad O\'Connor','Vogue – Madonna','Hold On – Wilson Phillips'],
  1991:['(Everything I Do) I Do It for You – Bryan Adams','One More Try – Timmy T','Gonna Make You Sweat – C+C Music Factory'],
  1992:['End of the Road – Boyz II Men','Jump – Kris Kross','Baby Got Back – Sir Mix-a-Lot'],
  1993:['I Will Always Love You – Whitney Houston','That\'s the Way Love Goes – Janet Jackson','Informer – Snow'],
  1994:['The Sign – Ace of Base','I\'ll Make Love to You – Boyz II Men','The Power of Love – Celine Dion'],
  1995:['Gangsta\'s Paradise – Coolio','Waterfalls – TLC','Creep – TLC'],
  1996:['Macarena – Los del Rio','One Sweet Day – Mariah Carey & Boyz II Men','Exhale – Whitney Houston'],
  1997:['Candle in the Wind – Elton John','MMMBop – Hanson','I\'ll Be Missing You – Puff Daddy & Faith Evans'],
  1998:['Too Close – Next','The Boy Is Mine – Brandy & Monica','You\'re Still the One – Shania Twain'],
  1999:['Believe – Cher','No Scrubs – TLC','Baby One More Time – Britney Spears'],
  2000:['Breathe – Faith Hill','Say My Name – Destiny\'s Child','Maria Maria – Santana ft. Product G&B'],
  2001:['Hanging by a Moment – Lifehouse','Fallin\' – Alicia Keys','Loverboy – Mariah Carey'],
  2002:['How You Remind Me – Nickelback','Complicated – Avril Lavigne','A Moment Like This – Kelly Clarkson'],
  2003:['In da Club – 50 Cent','Crazy in Love – Beyoncé ft. Jay-Z','Baby Boy – Beyoncé ft. Sean Paul'],
  2004:['Yeah! – Usher ft. Lil Jon & Ludacris','Burn – Usher','Confessions Part II – Usher'],
  2005:['We Belong Together – Mariah Carey','Hollaback Girl – Gwen Stefani','Since U Been Gone – Kelly Clarkson'],
  2006:['Bad Day – Daniel Powter','Temperature – Sean Paul','Promiscuous – Nelly Furtado ft. Timbaland'],
  2007:['Irreplaceable – Beyoncé','The Sweet Escape – Gwen Stefani','Girlfriend – Avril Lavigne'],
  2008:['Low – Flo Rida ft. T-Pain','Lollipop – Lil Wayne','Whatever You Like – T.I.'],
  2009:['Boom Boom Pow – Black Eyed Peas','Right Round – Flo Rida','Poker Face – Lady Gaga'],
  2010:['Tik Tok – Kesha','Need You Now – Lady Antebellum','Hey Soul Sister – Train'],
  2011:['Rolling in the Deep – Adele','Party Rock Anthem – LMFAO','Moves Like Jagger – Maroon 5'],
  2012:['Somebody That I Used to Know – Gotye ft. Kimbra','Call Me Maybe – Carly Rae Jepsen','Gangnam Style – PSY'],
  2013:['Thrift Shop – Macklemore & Ryan Lewis','Blurred Lines – Robin Thicke','Royals – Lorde'],
  2014:['Happy – Pharrell Williams','Dark Horse – Katy Perry','All of Me – John Legend'],
  2015:['Uptown Funk – Mark Ronson ft. Bruno Mars','See You Again – Wiz Khalifa','Thinking Out Loud – Ed Sheeran'],
  2016:['Love Yourself – Justin Bieber','Sorry – Justin Bieber','One Dance – Drake'],
  2017:['Shape of You – Ed Sheeran','Despacito – Luis Fonsi ft. Daddy Yankee','That\'s What I Like – Bruno Mars'],
  2018:['God\'s Plan – Drake','Perfect – Ed Sheeran','In My Feelings – Drake'],
  2019:['Old Town Road – Lil Nas X ft. Billy Ray Cyrus','Without Me – Halsey','7 Rings – Ariana Grande'],
  2020:['Blinding Lights – The Weeknd','Dynamite – BTS','Watermelon Sugar – Harry Styles'],
  2021:['drivers license – Olivia Rodrigo','Levitating – Dua Lipa','Save Your Tears – The Weeknd'],
  2022:['As It Was – Harry Styles','Heat Waves – Glass Animals','About Damn Time – Lizzo'],
  2023:['Flowers – Miley Cyrus','Kill Bill – SZA','Anti-Hero – Taylor Swift'],
  2024:['Espresso – Sabrina Carpenter','Beautiful Things – Benson Boone','Fortnight – Taylor Swift ft. Post Malone'],
};

window.FILM_DB = {
  1920:['The Kid – Charlie Chaplin','Way Down East – D.W. Griffith','The Mark of Zorro – Douglas Fairbanks'],
  1921:['The Four Horsemen of the Apocalypse – Rex Ingram','The Kid – Chaplin','Orphans of the Storm – Griffith'],
  1922:['Nosferatu – F.W. Murnau','Robin Hood – Allan Dwan','Dr. Mabuse the Gambler – Fritz Lang'],
  1923:['The Hunchback of Notre Dame','Safety Last! – Harold Lloyd','A Woman of Paris – Chaplin'],
  1924:['The Thief of Bagdad – Raoul Walsh','Greed – Erich von Stroheim','The Navigator – Keaton & Crisp'],
  1925:['The Gold Rush – Charlie Chaplin','Battleship Potemkin – Eisenstein','Ben-Hur – Fred Niblo'],
  1926:['The General – Buster Keaton','Metropolis (pre-release) – Fritz Lang','Don Juan – Alan Crosland'],
  1927:['Metropolis – Fritz Lang','The Jazz Singer – Alan Crosland','Wings – William Wellman'],
  1928:['The Crowd – King Vidor','Steamboat Willie – Walt Disney','The Wind – Victor Sjöström'],
  1929:['All Quiet on the Western Front (prod.)','The Broadway Melody','Pandora\'s Box – G.W. Pabst'],
  1930:['All Quiet on the Western Front – Lewis Milestone','Morocco – Josef von Sternberg','Hell\'s Angels – Howard Hughes'],
  1931:['Dracula – Tod Browning','Frankenstein – James Whale','City Lights – Charlie Chaplin'],
  1932:['Scarface – Howard Hawks','Grand Hotel – Edmund Goulding','Trouble in Paradise – Lubitsch'],
  1933:['King Kong – Cooper & Schoedsack','Duck Soup – Leo McCarey','42nd Street – Lloyd Bacon'],
  1934:['It Happened One Night – Frank Capra','The Thin Man – W.S. Van Dyke','Of Human Bondage – John Cromwell'],
  1935:['Mutiny on the Bounty – Frank Lloyd','A Night at the Opera – Sam Wood','Top Hat – Mark Sandrich'],
  1936:['Modern Times – Charlie Chaplin','Mr. Deeds Goes to Town – Capra','My Man Godfrey – Gregory La Cava'],
  1937:['Snow White and the Seven Dwarfs – Disney','The Awful Truth – Leo McCarey','A Star Is Born – William Wellman'],
  1938:['Bringing Up Baby – Howard Hawks','The Adventures of Robin Hood – Curtiz','Grand Illusion – Jean Renoir'],
  1939:['Gone with the Wind – Victor Fleming','The Wizard of Oz – Victor Fleming','Stagecoach – John Ford'],
  1940:['Rebecca – Alfred Hitchcock','The Philadelphia Story – George Cukor','The Great Dictator – Charlie Chaplin'],
  1941:['Citizen Kane – Orson Welles','The Maltese Falcon – John Huston','How Green Was My Valley – John Ford'],
  1942:['Casablanca – Michael Curtiz','Mrs. Miniver – William Wyler','Yankee Doodle Dandy – Michael Curtiz'],
  1943:['The More the Merrier – George Stevens','For Whom the Bell Tolls – Sam Wood','Shadow of a Doubt – Alfred Hitchcock'],
  1944:['Double Indemnity – Billy Wilder','Laura – Otto Preminger','To Have and Have Not – Howard Hawks'],
  1945:['Mildred Pierce – Michael Curtiz','Spellbound – Alfred Hitchcock','The Lost Weekend – Billy Wilder'],
  1946:['It\'s a Wonderful Life – Frank Capra','The Best Years of Our Lives – Wyler','Notorious – Alfred Hitchcock'],
  1947:['Miracle on 34th Street – George Seaton','Great Expectations – David Lean','Black Narcissus – Powell & Pressburger'],
  1948:['The Treasure of the Sierra Madre – Huston','The Red Shoes – Powell & Pressburger','Bicycle Thieves – De Sica'],
  1949:['The Third Man – Carol Reed','All the King\'s Men – Robert Rossen','The Heiress – William Wyler'],
  1950:['All About Eve – Joseph L. Mankiewicz','Sunset Boulevard – Billy Wilder','Rashomon – Akira Kurosawa'],
  1951:['A Streetcar Named Desire – Kazan','The African Queen – John Huston','An American in Paris – Vincente Minnelli'],
  1952:['Singin\' in the Rain – Kelly & Donen','High Noon – Fred Zinnemann','The Quiet Man – John Ford'],
  1953:['Roman Holiday – William Wyler','From Here to Eternity – Zinnemann','Shane – George Stevens'],
  1954:['Rear Window – Alfred Hitchcock','On the Waterfront – Elia Kazan','Seven Samurai – Akira Kurosawa'],
  1955:['Rebel Without a Cause – Nicholas Ray','Marty – Delbert Mann','The Night of the Hunter – Charles Laughton'],
  1956:['The Ten Commandments – Cecil B. DeMille','Giant – George Stevens','Around the World in 80 Days – Michael Anderson'],
  1957:['The Bridge on the River Kwai – Lean','12 Angry Men – Sidney Lumet','Paths of Glory – Stanley Kubrick'],
  1958:['Vertigo – Alfred Hitchcock','Touch of Evil – Orson Welles','Gigi – Vincente Minnelli'],
  1959:['Ben-Hur – William Wyler','Some Like It Hot – Billy Wilder','North by Northwest – Hitchcock'],
  1960:['Psycho – Alfred Hitchcock','Spartacus – Stanley Kubrick','The Apartment – Billy Wilder'],
  1961:['West Side Story – Wise & Robbins','Breakfast at Tiffany\'s – Blake Edwards','The Guns of Navarone – J. Lee Thompson'],
  1962:['Lawrence of Arabia – David Lean','To Kill a Mockingbird – Robert Mulligan','The Manchurian Candidate – Frankenheimer'],
  1963:['8½ – Federico Fellini','The Great Escape – John Sturges','Cleopatra – Joseph L. Mankiewicz'],
  1964:['Dr. Strangelove – Stanley Kubrick','A Hard Day\'s Night – Richard Lester','My Fair Lady – George Cukor'],
  1965:['The Sound of Music – Robert Wise','Doctor Zhivago – David Lean','For a Few Dollars More – Sergio Leone'],
  1966:['The Good the Bad and the Ugly – Leone','Blow-Up – Michelangelo Antonioni','A Man for All Seasons – Fred Zinnemann'],
  1967:['The Graduate – Mike Nichols','Bonnie and Clyde – Arthur Penn','In the Heat of the Night – Norman Jewison'],
  1968:['2001: A Space Odyssey – Kubrick','Rosemary\'s Baby – Roman Polanski','Planet of the Apes – Franklin J. Schaffner'],
  1969:['Midnight Cowboy – John Schlesinger','Easy Rider – Dennis Hopper','Butch Cassidy and the Sundance Kid – Roy Hill'],
  1970:['Patton – Franklin J. Schaffner','MASH – Robert Altman','Five Easy Pieces – Bob Rafelson'],
  1971:['A Clockwork Orange – Kubrick','The French Connection – William Friedkin','Dirty Harry – Don Siegel'],
  1972:['The Godfather – Francis Ford Coppola','Cabaret – Bob Fosse','Deliverance – John Boorman'],
  1973:['The Exorcist – William Friedkin','American Graffiti – George Lucas','Badlands – Terrence Malick'],
  1974:['The Godfather Part II – Coppola','Chinatown – Roman Polanski','Blazing Saddles – Mel Brooks'],
  1975:['Jaws – Steven Spielberg','One Flew Over the Cuckoo\'s Nest – Forman','Barry Lyndon – Stanley Kubrick'],
  1976:['Rocky – John G. Avildsen','Taxi Driver – Martin Scorsese','Network – Sidney Lumet'],
  1977:['Star Wars – George Lucas','Annie Hall – Woody Allen','Close Encounters of the Third Kind – Spielberg'],
  1978:['The Deer Hunter – Michael Cimino','Superman – Richard Donner','Midnight Express – Alan Parker'],
  1979:['Apocalypse Now – Coppola','Alien – Ridley Scott','Kramer vs. Kramer – Robert Benton'],
  1980:['The Empire Strikes Back – Irvin Kershner','Raging Bull – Martin Scorsese','The Shining – Stanley Kubrick'],
  1981:['Raiders of the Lost Ark – Spielberg','Chariots of Fire – Hugh Hudson','Das Boot – Wolfgang Petersen'],
  1982:['E.T. the Extra-Terrestrial – Spielberg','Blade Runner – Ridley Scott','Gandhi – Richard Attenborough'],
  1983:['Terms of Endearment – James L. Brooks','Scarface – Brian De Palma','The Right Stuff – Philip Kaufman'],
  1984:['Amadeus – Miloš Forman','The Terminator – James Cameron','Indiana Jones and the Temple of Doom – Spielberg'],
  1985:['Back to the Future – Robert Zemeckis','Witness – Peter Weir','The Color Purple – Spielberg'],
  1986:['Platoon – Oliver Stone','Top Gun – Tony Scott','Ferris Bueller\'s Day Off – John Hughes'],
  1987:['Full Metal Jacket – Kubrick','The Last Emperor – Bertolucci','Fatal Attraction – Adrian Lyne'],
  1988:['Rain Man – Barry Levinson','Die Hard – John McTiernan','Who Framed Roger Rabbit – Zemeckis'],
  1989:['Batman – Tim Burton','Indiana Jones and the Last Crusade – Spielberg','Born on the Fourth of July – Oliver Stone'],
  1990:['Goodfellas – Martin Scorsese','Home Alone – Chris Columbus','Dances with Wolves – Kevin Costner'],
  1991:['The Silence of the Lambs – Jonathan Demme','Terminator 2 – James Cameron','JFK – Oliver Stone'],
  1992:['Unforgiven – Clint Eastwood','Reservoir Dogs – Quentin Tarantino','The Player – Robert Altman'],
  1993:['Schindler\'s List – Steven Spielberg','Jurassic Park – Steven Spielberg','Groundhog Day – Harold Ramis'],
  1994:['The Shawshank Redemption – Frank Darabont','Pulp Fiction – Quentin Tarantino','Forrest Gump – Robert Zemeckis'],
  1995:['Se7en – David Fincher','Toy Story – John Lasseter','Braveheart – Mel Gibson'],
  1996:['Fargo – Coen Brothers','The English Patient – Anthony Minghella','Jerry Maguire – Cameron Crowe'],
  1997:['Titanic – James Cameron','Good Will Hunting – Gus Van Sant','L.A. Confidential – Curtis Hanson'],
  1998:['Saving Private Ryan – Spielberg','The Truman Show – Peter Weir','American History X – Tony Kaye'],
  1999:['The Matrix – Wachowskis','Fight Club – David Fincher','American Beauty – Sam Mendes'],
  2000:['Gladiator – Ridley Scott','Requiem for a Dream – Darren Aronofsky','Cast Away – Robert Zemeckis'],
  2001:['The Lord of the Rings: Fellowship – Peter Jackson','Mulholland Drive – David Lynch','A Beautiful Mind – Ron Howard'],
  2002:['The Pianist – Roman Polanski','The Hours – Stephen Daldry','Chicago – Rob Marshall'],
  2003:['Lord of the Rings: Return of the King – Jackson','Lost in Translation – Sofia Coppola','Mystic River – Clint Eastwood'],
  2004:['Eternal Sunshine of the Spotless Mind – Gondry','Million Dollar Baby – Eastwood','Sideways – Alexander Payne'],
  2005:['Brokeback Mountain – Ang Lee','Crash – Paul Haggis','Munich – Steven Spielberg'],
  2006:['The Departed – Martin Scorsese','Pan\'s Labyrinth – Guillermo del Toro','Children of Men – Alfonso Cuarón'],
  2007:['No Country for Old Men – Coen Brothers','There Will Be Blood – P.T. Anderson','The Assassination of Jesse James – Andrew Dominik'],
  2008:['The Dark Knight – Christopher Nolan','Slumdog Millionaire – Danny Boyle','WALL-E – Andrew Stanton'],
  2009:['Up – Pete Docter','Inglourious Basterds – Tarantino','Avatar – James Cameron'],
  2010:['Inception – Christopher Nolan','The Social Network – David Fincher','Black Swan – Darren Aronofsky'],
  2011:['The Artist – Michel Hazanavicius','Drive – Nicolas Winding Refn','Midnight in Paris – Woody Allen'],
  2012:['The Dark Knight Rises – Nolan','Argo – Ben Affleck','Life of Pi – Ang Lee'],
  2013:['Gravity – Alfonso Cuarón','12 Years a Slave – Steve McQueen','Her – Spike Jonze'],
  2014:['Interstellar – Christopher Nolan','Boyhood – Richard Linklater','Birdman – Alejandro G. Iñárritu'],
  2015:['Mad Max: Fury Road – George Miller','The Revenant – Iñárritu','Spotlight – Tom McCarthy'],
  2016:['Moonlight – Barry Jenkins','Manchester by the Sea – Kenneth Lonergan','La La Land – Damien Chazelle'],
  2017:['Get Out – Jordan Peele','Dunkirk – Christopher Nolan','Blade Runner 2049 – Denis Villeneuve'],
  2018:['Roma – Alfonso Cuarón','A Quiet Place – John Krasinski','Avengers: Infinity War – Russo Brothers'],
  2019:['Parasite – Bong Joon-ho','1917 – Sam Mendes','Joker – Todd Phillips'],
  2020:['Soul – Pete Docter','Nomadland – Chloé Zhao','Tenet – Christopher Nolan'],
  2021:['The Power of the Dog – Jane Campion','Dune – Denis Villeneuve','Spider-Man: No Way Home – Jon Watts'],
  2022:['Everything Everywhere All at Once – Daniels','The Fabelmans – Spielberg','Top Gun: Maverick – Joseph Kosinski'],
  2023:['Oppenheimer – Christopher Nolan','Barbie – Greta Gerwig','Past Lives – Celine Song'],
  2024:['Dune: Part Two – Denis Villeneuve','Inside Out 2 – Kelsey Mann','Alien: Romulus – Fede Álvarez'],
};

/* Helper: find closest year in a database object */
window.closestYear = function(db, y) {
  const keys = Object.keys(db).map(Number).sort((a,b) => a-b);
  return keys.reduce((a,b) => Math.abs(b-y) < Math.abs(a-y) ? b : a);
};
